export const CONTINUE_LEARNING = [
  {
    id: 1,
    title: "UI/UX Design Fundamentals",
    author: "Oliver Gasner",
    lesson: "Lesson 14",
    duration: "4m left",
    progress: 75,
    image: "https://images.unsplash.com/photo-1626785774573-4b799315345d?q=80&w=400&auto=format&fit=crop",
    primaryAction: true,
  },
  {
    id: 2,
    title: "Web Development Basics",
    author: "Sharon Abraham",
    lesson: "Lesson 8",
    duration: "1hr 55m left",
    progress: 50,
    image: "https://images.unsplash.com/photo-1498050108023-c5249f4df085?q=80&w=800&auto=format&fit=crop",
    primaryAction: false,
  },
];

export const ENROLLED_COURSES = [
  {
    id: 1,
    title: "UI/UX Design Fundamental",
    author: "Oliver Gasner",
    progress: 75,
    image: "https://images.unsplash.com/photo-1626785774573-4b799315345d?q=80&w=400&auto=format&fit=crop",
    lesson: "",
    duration: "",
  },
  {
    id: 2,
    title: "Web Development Basics",
    author: "Sharon Abraham",
    progress: 50,
    image: "https://images.unsplash.com/photo-1587620962725-abab7fe55159?q=80&w=400&auto=format&fit=crop",
    lesson: "",
    duration: "",
  },
  {
    id: 3,
    title: "Time Management",
    author: "Praise Mba",
    progress: 80,
    image: "https://images.unsplash.com/photo-1434030216411-0b793f4b4173?q=80&w=400&auto=format&fit=crop",
    lesson: "",
    duration: "",
  },
  {
    id: 4,
    title: "UI/UX Design Fundamental",
    author: "Oliver Gasner",
    progress: 75,
    image: "https://images.unsplash.com/photo-1626785774573-4b799315345d?q=80&w=400&auto=format&fit=crop",
    lesson: "",
    duration: "",
  },
  {
    id: 5,
    title: "Web Development Basics",
    author: "Sharon Abraham",
    progress: 50,
    image: "https://images.unsplash.com/photo-1587620962725-abab7fe55159?q=80&w=400&auto=format&fit=crop",
    lesson: "",
    duration: "",
  },
  {
    id: 6,
    title: "Time Management",
    author: "Praise Mba",
    progress: 80,
    image: "https://images.unsplash.com/photo-1434030216411-0b793f4b4173?q=80&w=400&auto=format&fit=crop",
    lesson: "",
    duration: "",
  },
];

export const COMPLETED_COURSES = [
  {
    id: 4,
    title: "Workplace Skills",
    author: "Career Development",
    progress: 100,
    image: "https://images.unsplash.com/photo-1552664730-d307ca884978?q=80&w=400&auto=format&fit=crop",
    lesson: "All Lessons",
    duration: "Completed",
  },
  {
    id: 5,
    title: "Microsoft AI Skills",
    author: "Microsoft",
    progress: 100,
    image: "https://images.unsplash.com/photo-1677442136019-21780ecad995?q=80&w=400&auto=format&fit=crop",
    lesson: "All Lessons",
    duration: "Completed",
  },
  {
    id: 6,
    title: "Talentflow Introduction",
    author: "Talentflow Team",
    progress: 100,
    image: "https://images.unsplash.com/photo-1551434678-e076c223a692?q=80&w=400&auto=format&fit=crop",
    lesson: "All Lessons",
    duration: "Completed",
  },
];

export const ADMIN_STATS = [
  { 
    label: 'Total users', 
    value: '2,340', 
    change: '+120', 
    period: 'This month' 
  },
  { 
    label: 'Total Courses', 
    value: '120', 
    change: '+8', 
    period: 'This week' 
  },
  { 
    label: 'Active users', 
    value: '1,120', 
    change: '+95', 
    period: 'Right now' 
  },
];

export const COURSES_CATALOG = [
  {
    id: 7,
    title: "Workplace Skills",
    author: "Career Development",
    image: "https://images.unsplash.com/photo-1552664730-d307ca884978?q=80&w=400&auto=format&fit=crop",
    lesson: "All Lessons",
    duration: "Completed",
    rating: 3,
    isPopular: false,
    isRecommended: true,
    category: "design",
    level: "beginner",
    price: "free",
  },
  {
    id: 8,
    title: "Microsoft AI Skills",
    author: "Microsoft",
    rating: 4,
    image: "https://images.unsplash.com/photo-1677442136019-21780ecad995?q=80&w=400&auto=format&fit=crop",
    lesson: "All Lessons",
    duration: "Completed",
    isPopular: true,
    isRecommended: true,
    category: "dev" ,
    level: "advanced",
    price: "paid",
  },
  {
    id: 9,
    title: "Talentflow Introduction",
    author: "Talentflow Team",
    rating: 5,
    image: "https://images.unsplash.com/photo-1551434678-e076c223a692?q=80&w=400&auto=format&fit=crop",
    lesson: "All Lessons",
    duration: "Completed",
    isPopular: true,
    isRecommended: false,
    category: "business",
    level: "advanced",
    price: "free",
  },
  {
    id: 10,
    title: "UX Design Fundamentals",
    author: "Google UX",
    rating: 4.5,
    image: "https://images.unsplash.com/photo-1581291518857-4e27b48ff24e?q=80&w=400&auto=format&fit=crop",
    lesson: "12 Lessons",
    duration: "2h 30min",
    isPopular: true,
    isRecommended: true,
    category: "business",
    level: "advanced",
    price: "free",
  },
  {
    id: 11,
    title: "Frontend Development Basics",
    author: "Meta",
    rating: 4.2,
    image: "https://images.unsplash.com/photo-1461749280684-dccba630e2f6?q=80&w=400&auto=format&fit=crop",
    lesson: "18 Lessons",
    duration: "3h",
    isPopular: true,
    isRecommended: false,
    category: "dev" ,
    level: "advanced",
    price: "paid",
  },
  {
    id: 12,
    title: "Data Analysis with Python",
    author: "IBM",
    rating: 4.7,
    image: "https://images.unsplash.com/photo-1551288049-bebda4e38f71?q=80&w=400&auto=format&fit=crop",
    lesson: "20 Lessons",
    duration: "4h",
    isPopular: false,
    isRecommended: true,
    category: "business",
    level: "advanced",
    price: "free",
  },
  {
    id: 13,
    title: "Product Management Essentials",
    author: "Atlassian",
    rating: 4.1,
    image: "https://images.unsplash.com/photo-1559028012-481c04fa702d?q=80&w=400&auto=format&fit=crop",
    lesson: "10 Lessons",
    duration: "1h 45min",
    isPopular: false,
    isRecommended: true,
    category: "dev" ,
    level: "advanced",
    price: "paid",
  },
  {
    id: 14,
    title: "Mobile App Design",
    author: "DesignLab",
    rating: 3.8,
    image: "https://images.unsplash.com/photo-1512941937669-90a1b58e7e9c?q=80&w=400&auto=format&fit=crop",
    lesson: "14 Lessons",
    duration: "2h",
    isPopular: false,
    isRecommended: false,
    category: "dev" ,
    level: "advanced",
    price: "paid",
  },
  {
    id: 15,
    title: "Cybersecurity Basics",
    author: "Cisco",
    rating: 4.6,
    image: "https://images.unsplash.com/photo-1510511233900-1982d92bd835?q=80&w=400&auto=format&fit=crop",
    lesson: "16 Lessons",
    duration: "3h 20min",
    isPopular: true,
    isRecommended: false,
    category: "dev" ,
    level: "advanced",
    price: "paid",
  },
  {
    id: 16,
    title: "Cloud Computing Fundamentals",
    author: "AWS",
    rating: 4.4,
    image: "https://images.unsplash.com/photo-1451187580459-43490279c0fa?q=80&w=400&auto=format&fit=crop",
    lesson: "15 Lessons",
    duration: "2h 50min",
    isPopular: true,
    isRecommended: false,
    category: "business",
    level: "advanced",
    price: "free",
  },
  {
    id: 17,
    title: "Soft Skills for Developers",
    author: "OpenClassrooms",
    rating: 3.9,
    image: "https://images.unsplash.com/photo-1521737604893-d14cc237f11d?q=80&w=400&auto=format&fit=crop",
    lesson: "8 Lessons",
    duration: "1h 20min",
    isPopular: false,
    isRecommended: true,
    category: "business",
    level: "advanced",
    price: "free",
  },
  {
    id: 18,
    title: "DevOps Introduction",
    author: "Docker",
    rating: 4.3,
    image: "https://images.unsplash.com/photo-1605902711622-cfb43c44367f?q=80&w=400&auto=format&fit=crop",
    lesson: "11 Lessons",
    duration: "2h 10min",
    isPopular: true,
    isRecommended: false,
    category: "business",
    level: "advanced",
    price: "free",
  }
];

export const TEAMS = [
  { id: 1, name: "Team Lima", membersCount: 23, color: "bg-blue-500", tags: ["UI/UX", "Frontend", "Backend", "Product Management"] },
  { id: 2, name: "Team Raya", membersCount: 21, color: "bg-indigo-500", tags: ["UI/UX", "Frontend", "Backend", "Product Management"] },
  { id: 3, name: "Team Mira", membersCount: 25, color: "bg-purple-500", tags: ["UI/UX", "Frontend", "Product Management"] },
];

export const MY_TEAM_MEMBERS = [
  { id: 1, name: "Ayankola Precious", skill: "Project Manager", role: "Team Lead", image: "/avatars/precious.jpg" },
  { id: 2, name: "Ayankola Precious", skill: "Project Manager", role: "Assistant", image: "/avatars/precious.jpg" },
  { id: 3, name: "Ayankola Precious", skill: "Project Manager", role: "Assistant 2", image: "/avatars/precious.jpg" },
  { id: 4, name: "Ayankola Precious", skill: "Graphic Design", role: "Member", image: "/avatars/precious.jpg" },
];