export const demoActiveCourses = [
  {
    author: "By Aisha Bello",
    cta: "Continue",
    href: "/learner/course-catalog",
    image: "/course-card-1.webp",
    meta: "Lesson 6 . 2 hrs left",
    progress: 68,
    title: "UIUX Design Fundamentals",
  },
  {
    author: "By Michael Chen",
    cta: "Continue",
    href: "/learner/course-catalog",
    image: "/course-card-3.webp",
    meta: "Lesson 4 . 1 hr left",
    progress: 42,
    title: "Frontend Foundations",
  },
  {
    author: "By Grace Williams",
    cta: "Continue",
    href: "/learner/course-catalog",
    image: "/course-5.webp",
    meta: "Lesson 3 . 45 mins left",
    progress: 24,
    title: "Product Design Sprint",
  },
] as const;

export const demoCompletedCourses = [
  {
    cta: "View",
    href: "/learner/certificate",
    image: "/course-4.webp",
    meta: "All . Completed",
    progress: 100,
    title: "Workplace Skills",
  },
  {
    cta: "View",
    href: "/learner/certificate",
    image: "/course-card-3.webp",
    meta: "All . Completed",
    progress: 100,
    title: "Microsoft AI Skills",
  },
  {
    cta: "View",
    href: "/learner/certificate",
    image: "/course-6.webp",
    meta: "All . Completed",
    progress: 100,
    title: "Talentflow Introduction",
  },
  {
    cta: "View",
    href: "/learner/certificate",
    image: "/course-7.webp",
    meta: "All . Completed",
    progress: 100,
    title: "Truemind Basics",
  },
  {
    cta: "View",
    href: "/learner/certificate",
    image: "/Frame 143 (3).webp",
    meta: "All . Completed",
    progress: 100,
    title: "Career Readiness Essentials",
  },
  {
    cta: "View",
    href: "/learner/certificate",
    image: "/course-1.webp",
    meta: "All . Completed",
    progress: 100,
    title: "Communication at Work",
  },
  {
    cta: "View",
    href: "/learner/certificate",
    image: "/course-card-2.webp",
    meta: "All . Completed",
    progress: 100,
    title: "Digital Productivity",
  },
  {
    cta: "View",
    href: "/learner/certificate",
    image: "/course-8.webp",
    meta: "All . Completed",
    progress: 100,
    title: "Team Collaboration Basics",
  },
] as const;
